---
 - hosts: localhost
   connection: local
   roles:
     - ansible-i3
     - ansible-neomutt
     - ansible-polybar
     - ansible-termite
     - ansible-tmux
     - ansible-vim
     - ansible-xresources
     - ansible-zsh
     # - ansible-alacritty
     # - ansible-fonts
