---
 - hosts: kartoffel
   roles:
     - ansible-xresources
     - ansible-vim

 - hosts: zitrone
   roles:
     - ansible-xresources
     - ansible-vim

 - hosts: lauch
   roles:
     - ansible-vim

 - hosts: buche
   roles:
     - ansible-vim


