---
 - hosts: kartoffel
   roles:
     - ansible-xresources
     - ansible-vim
     - ansible-i3
     - ansible-termite
     - ansible-neomutt
     - ansible-tmux

 - hosts: zitrone
   roles:
     - ansible-xresources
     - ansible-vim
     - ansible-i3
     - ansible-termite
     - ansible-neomutt
     - ansible-tmux

 - hosts: lauch
   roles:
     - ansible-vim
     - ansible-tmux

 - hosts: buche
   roles:
     - ansible-vim
     - ansible-tmux


