---
 - hosts: kartoffel
   roles:
     - ansible-xresources
     - ansible-alacritty
     # - ansible-vim
     - ansible-i3
     - ansible-termite
     - ansible-neomutt
     - ansible-tmux
     - ansible-polybar
     - ansible-zsh
     # - ansible-xscreensaver
     #
 - hosts: void
   roles:
     - ansible-alacritty
     - ansible-fonts
     - ansible-xresources
     - ansible-vim
     - ansible-i3
     - ansible-termite
     - ansible-neomutt
     - ansible-tmux
     - ansible-polybar
     - ansible-zsh
     # - ansible-xscreensaver

 - hosts: zitrone
   roles:
     - ansible-alacritty
     - ansible-xresources
     - ansible-vim
     - ansible-i3
     - ansible-termite
     - ansible-neomutt
     - ansible-tmux
     - ansible-polybar
     - ansible-zsh
     # - ansible-xscreensaver

 - hosts: analysis-poc
   roles:
     - ansible-xresources
     - ansible-alacritty
     - ansible-vim
     - ansible-i3
     - ansible-termite
     - ansible-neomutt
     - ansible-tmux
     - ansible-polybar
     - ansible-zsh
     # - ansible-xscreensaver

 - hosts: lauch
   roles:
     - ansible-vim
     - ansible-tmux
     - ansible-zsh

 - hosts: birne
   roles:
     - ansible-vim
     - ansible-tmux
     - ansible-zsh

 - hosts: kfbox
   roles:
     - ansible-vim
     - ansible-tmux
     - ansible-zsh

 - hosts: buche
   roles:
     - ansible-vim
     - ansible-tmux
     - ansible-zsh


